version: '3.8'

services:
  client: 
    stdin_open: true
    container_name: teste-react-build
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - '4000:4000'